// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqd3d8HszSQmL8sHgNUPpUMaU5ZkckMXg',
    appId: '1:149262815547:web:6a6fb9ce9d6d785545e71e',
    messagingSenderId: '149262815547',
    projectId: 'm2miaged',
    authDomain: 'm2miaged.firebaseapp.com',
    storageBucket: 'm2miaged.appspot.com',
    measurementId: 'G-6WPN0Q6CL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCE0dqeQeXmjSwZM7LOXg4m1C1etdb2-k',
    appId: '1:149262815547:android:f14b9ef63bb0ff8b45e71e',
    messagingSenderId: '149262815547',
    projectId: 'm2miaged',
    storageBucket: 'm2miaged.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2TqvUWnobrPAiW4SaxTNmesQ5k927luw',
    appId: '1:149262815547:ios:2c82e9299ef1133445e71e',
    messagingSenderId: '149262815547',
    projectId: 'm2miaged',
    storageBucket: 'm2miaged.appspot.com',
    iosClientId: '149262815547-pkrm3n0mgmkp3ogjgfvm4o27e55lc7v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.miaged',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2TqvUWnobrPAiW4SaxTNmesQ5k927luw',
    appId: '1:149262815547:ios:2c82e9299ef1133445e71e',
    messagingSenderId: '149262815547',
    projectId: 'm2miaged',
    storageBucket: 'm2miaged.appspot.com',
    iosClientId: '149262815547-pkrm3n0mgmkp3ogjgfvm4o27e55lc7v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.miaged',
  );
}
